@startuml

actor loop


create "client : PubSubClient"

    loop !Conectado
        loop -> "client : PubSubClient" : connected()
    end

    loop -> "client : PubSubClient" : loop()

    alt sample Time < t transcurrido
        loop -> "client : PubSubClient" : publish()
    end

@enduml